// <auto-generated />
namespace AITECRM.Migrations.AITE
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ini1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ini1));
        
        string IMigrationMetadata.Id
        {
            get { return "201807251049185_Ini1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
